spring:
  application:
    name: template-app
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

management:
  server:
    port: 8082
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

info:
  app:
    name: template App
    description: This is my template app
    version: #project.version#

logging:
  level:
    root: info
    org.mauro:  debug
