spring:
  application:
    name: template-app
  main:
    lazy-initialization: true
  config:
    location: file://./src/main/resources/application.yml
  jmx:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
  flyway:
    mixed: true

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

management:
  server:
    port: 8082
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@